spring:
  cloud:
    gateway:
      routes:
        - id: microadmin-route
          uri: lb://MICROADMIN
          predicates:
            - Path=/MICROADMIN/**
          filters:
            - StripPrefix=1
        - id: microfacture-route
          uri: lb://MICROFACTURE
          predicates:
            - Path=/MICROFACTURE/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
