spring:
  cloud:
    gateway:
      routes:
        - id: microadmin-route
          uri: lb://MICROADMIN
          predicates:
            - Path=/MICROADMIN/**
          filters:
            - StripPrefix=1
        - id: microfacture-route
          uri: lb://MICROFACTURE
          predicates:
            - Path=/MICROFACTURE/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException

  ratelimiter:
    instances:
      defaultRateLimiter:
        register-health-indicator: true
        limit-for-period: 50
        limit-refresh-period: 1s


management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


